# Generated by Django 5.0.10 on 2025-01-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
